### ISSUE TITLE
URL Templates in metrics plugin

### ISSUE THREAD

**Issue by serpi90** [ba-st/Stargate#106]
A new metric with the URL template, not the fully resolved URL would be nice.

It's almost impossible to aggregate them later (it needs to be done case by case which is not maintainable in the long term).

Currently, you get metrics for:
`http://example.com/pets/1/favourite-foods/3`
`http://example.com/pets/1/favourite-foods/2`
`http://example.com/pets/4/favourite-foods/3`
`http://example.com/pets/7/favourite-foods?type=fish`
I think it would be better if we can provide something like this:
`/pets/<pet-uuid>/favourite-foods/<food-uuid>` 
`/pets/<pet-uuid>/favourite-foods` 

Ideally, it would be a label on top of the current metrics:
```
http_request_count{url="http://example.com/pets/741/metrics",...,url_template="/pets/741"} 1 1593204634530
```

But if not possible, a new metric with template_url instead of URL would also be useful.

**Comment by gcotelli** [comment]
I've implemented it, but by now it only works if you set the logging level at least to 2. I've opened svenvc/zinc#55 : if it gets implemented then this can also work for logging level at 1.
