### ISSUE TITLE
Access-Control-Allow-Origin should have a valid Origin

### ISSUE THREAD

**Issue by jvanecek** [ba-st/Stargate#126]
Currently, Access-Control-Allow-Origin in the response has the origin with the trailing slash, which is not a valid origin format, and may never match the one the browser put in the request, and thus arise a blocked by cors policy in the browser. 
Ref: https://fetch.spec.whatwg.org/#http-access-control-allow-origin

**Comment by gcotelli** [comment]
Fixed by #127
