### ISSUE TITLE
Impossibility to configure error handler to the JRPC requests

### ISSUE THREAD

**Issue by jvanecek** [ba-st/Stargate#129]
Currently, the proper way to configure an error handler to the JRPC request is using `JRPCMessageProcessor>>#addErrorHandler:`. But that is imposible with actual `JsonRPCRequestHandler`, and there is no easy way to reuse the ones configured in `HTTPBasedRESTfulAPI`

**Comment by gcotelli** [comment]
This issues needs https://github.com/juliendelplanque/JRPC/pull/44
