### ISSUE TITLE
Operational Plugin: Health check

### ISSUE THREAD

**Issue by gcotelli** [ba-st/Stargate#40]
One of the operational plugins (#41) .
- Endpoint `/operations/health-check`
- Must be possible to configure this plugin with additional checks to be run.
- In case there are multiple checks the general status will be the worst status of the check runs and every check status can be accessed asking for the details media type and looking at the `details` object.
- A POST operation with the summary media type can be requested without Authorization, the rest requires an authenticated request with the proper authorization credentials.

## Supported operations:
- Run a health check and report the status: `POST` - `application/vnd.stargate.health-check.summary+json`
- Run a health check and report a detailed status: `POST` - `application/vnd.stargate.health-check.details+json`

## Supported statuses

|Status Keyword|HTTP Status Code|Description|
|-------------------|-------------------------|---|
|**PASS**|200 OK|The service is fully operational|
|**WARN**|200 OK|The service is responding but with degraded performance|
|**FAIL**|503 Service Unavailable|The service endpoints are not responding reliably|

**Comment by serpi90** [comment]
I would prefer `/health-check` or `/status` instead of `/health`, anyways this should be customizable, in case it conflicts with another entry-point.

**Comment by gcotelli** [comment]
Review https://inadarei.github.io/rfc-healthcheck/

**Comment by gcotelli** [comment]
Fixed in #60
