### ISSUE TITLE
Operational plugins

### ISSUE THREAD

**Issue by gcotelli** [ba-st/Stargate#41]
Provide some common abstractions that can be used to implement operational plugins.
An operational plugin must have the following characteristics:
- [x] Must expose operational info and can allow to control some operation
- [x] It's optional. It can be enabled by default but should be possible to disable them
- [x] Must expose at least an endpoint to access it's functionality under `/operations/{{plugin-endpoint}}`
- [x] Must be secured with a proper authorization filter. In specific situations a plugin can respond with some basic data in case there is no authorization (for example a basic healthcheck) but this behavior must be the exception to the rule.
- #75 Should be possible to enable/disable/configure it on the fly using an API endpoint (given the proper authorization credentials) using the media controls provided in the plugin representation/

## Plugin ideas:
- [x] Health Check: #40 
- [x] Configuration #42
- [x] Application Info #43
- [x] Loggers #44 
- [x] Application Control #45 
- [x] Metrics #46

## List available plugins
Available plugins including it's status (enabled/disable) and a list of media controls can be accessed doing a `GET` request to `/operations` with a supported media type.
Example:
```http
GET /operations
Accepts: application/json
```

```json
{
  "application-name" : "demo-app",
  "links": {
    "health": { "self": "/operations/health", "status": "ENABLED"},
    "info": {"self": "/operations/info", "status": "DISABLED"},
    ...
  }
}  
```

**Comment by serpi90** [comment]
> Must be secured with a proper authorization filter.
Healthcheck should not be behind authorization, at least not the most basic ok/not-ok
> Should be possible to enable/disable/configure it on the fly
Using application starter with --flags? via API using an entrypoint? unless this is intentionally left without details, i think it's unclear what this means.
